-- MySQL Script generated by MySQL Workbench
-- sex 18 jan 2019 12:59:17 -03
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema bd_svcv
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema bd_svcv
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `bd_svcv` DEFAULT CHARACTER SET utf8 ;
USE `bd_svcv` ;

-- -----------------------------------------------------
-- Table `bd_svcv`.`Endereco`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd_svcv`.`Endereco` (
  `idEndereco` INT NOT NULL AUTO_INCREMENT,
  `CEP` CHAR(8) NOT NULL,
  `Rua` VARCHAR(45) NULL,
  `Numero` INT NULL,
  `Bairro` VARCHAR(45) NULL,
  `Cidade` VARCHAR(45) NULL,
  `Estado` CHAR(2) NULL,
  PRIMARY KEY (`idEndereco`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `bd_svcv`.`Cliente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd_svcv`.`Cliente` (
  `idCliente` INT NOT NULL AUTO_INCREMENT,
  `CPF` CHAR(11) NOT NULL,
  `Nome` VARCHAR(45) NOT NULL,
  `Data_Nascimento` DATE NOT NULL,
  `Telefone` VARCHAR(11) NULL COMMENT '	',
  `E-mail` VARCHAR(100) NULL,
  `idEndereco` INT NOT NULL,
  PRIMARY KEY (`idCliente`),
  INDEX `fk_Cliente_Endereco1_idx` (`idEndereco` ASC),
  UNIQUE INDEX `CPF_UNIQUE` (`CPF` ASC),
  CONSTRAINT `fk_Cliente_Endereco1`
    FOREIGN KEY (`idEndereco`)
    REFERENCES `bd_svcv`.`Endereco` (`idEndereco`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `bd_svcv`.`Funcionario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd_svcv`.`Funcionario` (
  `idFuncionario` INT NOT NULL AUTO_INCREMENT,
  `CPF` CHAR(11) NOT NULL COMMENT '	',
  `Nome` VARCHAR(45) NULL,
  `Usuario` VARCHAR(10) NOT NULL,
  `Senha` VARCHAR(20) NOT NULL,
  `Data_Nascimento` DATE NOT NULL COMMENT '		',
  `E-mail` VARCHAR(100) NULL,
  `Telefone` CHAR(11) NULL,
  PRIMARY KEY (`idFuncionario`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `bd_svcv`.`Veiculo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd_svcv`.`Veiculo` (
  `idVeiculo` INT NOT NULL AUTO_INCREMENT,
  `Modelo` VARCHAR(64) NOT NULL,
  `Chassi` CHAR(17) NOT NULL,
  `Marca` VARCHAR(32) NOT NULL,
  `Portas` INT NULL,
  `Cor` VARCHAR(10) NULL,
  `Placa` CHAR(7) NULL,
  `Câmbio` VARCHAR(45) NULL,
  `Preco_min` DECIMAL(10,2) NULL,
  `Preco_ven` DECIMAL(10,2) NULL,
  `Ano` INT NULL,
  `Quilometragem` INT NULL,
  `Descricao` TEXT NULL,
  `Combustivel` VARCHAR(15) NULL,
  PRIMARY KEY (`idVeiculo`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `bd_svcv`.`Venda`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd_svcv`.`Venda` (
  `idCliente` INT NOT NULL,
  `idVeiculo` INT NOT NULL,
  `idFuncionario` INT NOT NULL,
  `Dat_Hor_Venda` DATETIME NULL,
  `Dat_Hor_Pag` DATETIME NULL,
  `Valor` DECIMAL(8,2),
  PRIMARY KEY (`idCliente`, `idVeiculo`),
  INDEX `fk_Cliente_has_Veiculo_Veiculo1_idx` (`idVeiculo` ASC),
  INDEX `fk_Cliente_has_Veiculo_Cliente_idx` (`idCliente` ASC),
  INDEX `fk_Cliente_has_Veiculo_Funcionario1_idx` (`idFuncionario` ASC),
  CONSTRAINT `fk_Cliente_has_Veiculo_Cliente`
    FOREIGN KEY (`idCliente`)
    REFERENCES `bd_svcv`.`Cliente` (`idCliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Cliente_has_Veiculo_Veiculo1`
    FOREIGN KEY (`idVeiculo`)
    REFERENCES `bd_svcv`.`Veiculo` (`idVeiculo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Cliente_has_Veiculo_Funcionario1`
    FOREIGN KEY (`idFuncionario`)
    REFERENCES `bd_svcv`.`Funcionario` (`idFuncionario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `bd_svcv`.`Fornecedor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd_svcv`.`Fornecedor` (
  `idFornecedor` INT NOT NULL AUTO_INCREMENT,
  `Razao_Social` VARCHAR(100) NULL,
  `Nome_Fantasia` VARCHAR(45) NULL,
  `CNPJ` CHAR(14) NULL,
  `idEndereco` INT NOT NULL,
  `Telefone` CHAR(10) NULL,
  PRIMARY KEY (`idFornecedor`),
  INDEX `fk_Fornecedor_Endereco1_idx` (`idEndereco` ASC),
  CONSTRAINT `fk_Fornecedor_Endereco1`
    FOREIGN KEY (`idEndereco`)
    REFERENCES `bd_svcv`.`Endereco` (`idEndereco`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `bd_svcv`.`Compra_PJ`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd_svcv`.`Compra_PJ` (
  `idCompra_PJ` INT NOT NULL AUTO_INCREMENT,
  `Dat_Hor_Compra` DATETIME NULL,
  `Dat_Hor_Pag` DATETIME NULL,
  `Valor` DECIMAL(10,2) NULL DEFAULT 0,
  `idFornecedor` INT NOT NULL,
  PRIMARY KEY (`idCompra_PJ`),
  INDEX `fk_Compra_PJ_Fornecedor1_idx` (`idFornecedor` ASC),
  CONSTRAINT `fk_Compra_PJ_Fornecedor1`
    FOREIGN KEY (`idFornecedor`)
    REFERENCES `bd_svcv`.`Fornecedor` (`idFornecedor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `bd_svcv`.`Item_Compra`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd_svcv`.`ItemCompra` (
  `idCompra_PJ` INT NOT NULL,
  `idVeiculo` INT NOT NULL,
  `Valor` DECIMAL(10,2) NULL,
  PRIMARY KEY (`idCompra_PJ`, `idVeiculo`),
  INDEX `fk_Compra_PJ_has_Veiculo_Veiculo1_idx` (`idVeiculo` ASC),
  INDEX `fk_Compra_PJ_has_Veiculo_Compra_PJ1_idx` (`idCompra_PJ` ASC),
  CONSTRAINT `fk_Compra_PJ_has_Veiculo_Compra_PJ1`
    FOREIGN KEY (`idCompra_PJ`)
    REFERENCES `bd_svcv`.`Compra_PJ` (`idCompra_PJ`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Compra_PJ_has_Veiculo_Veiculo1`
    FOREIGN KEY (`idVeiculo`)
    REFERENCES `bd_svcv`.`Veiculo` (`idVeiculo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `bd_svcv`.`Compra_PF`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd_svcv`.`Compra_PF` (
  `idCliente` INT NOT NULL,
  `idFuncionario` INT NOT NULL,
  `idVeiculo` INT NOT NULL,
  `Dat_Hor_Compra` DATETIME NULL,
  `Dat_Hor_Pag` DATETIME NULL,
  `Valor` DECIMAL(10,2) NULL,
  PRIMARY KEY (`idCliente`, `idVeiculo`),
  INDEX `fk_Cliente_has_Veiculo_Funcionario2_idx` (`idFuncionario` ASC),
  INDEX `fk_Cliente_has_Veiculo_Veiculo2_idx` (`idVeiculo` ASC),
  CONSTRAINT `fk_Cliente_has_Veiculo_Cliente1`
    FOREIGN KEY (`idCliente`)
    REFERENCES `bd_svcv`.`Cliente` (`idCliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Cliente_has_Veiculo_Funcionario2`
    FOREIGN KEY (`idFuncionario`)
    REFERENCES `bd_svcv`.`Funcionario` (`idFuncionario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Cliente_has_Veiculo_Veiculo2`
    FOREIGN KEY (`idVeiculo`)
    REFERENCES `bd_svcv`.`Veiculo` (`idVeiculo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

-- >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>> VIEWs, TRIGGERs e PROCEDUREs <<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<

-- View para saber o modelo mais vendido  *Pode ser melhorado para saber em um determinado período (Ultimos 30 dias);
-- select * from venda;
CREATE OR REPLACE VIEW vw_maisVend 
AS SELECT Modelo, count(Modelo) as Quantidade_Vendida from bd_svcv.Venda natural join bd_svcv.Veiculo
where Dat_Hor_Venda between current_date() - 30 and current_date() group by Modelo order by Quantidade_Vendida desc;

-- View para saber as vendas dos últimos Trinta dias;
SELECT * FROM vw_last30;
select * from venda;
CREATE OR REPLACE VIEW vw_last30
AS select Nome 'Cliente', Modelo 'Veiculo', Marca 'Marca', Dat_Hor_Venda 'Data e Hora', Valor 'Preço de Venda' 
from cliente natural join venda natural join veiculo
where Dat_Hor_Venda BETWEEN date_add( current_date(), INTERVAL-30 DAY) and current_date() order by Dat_Hor_Venda;

-- View para saber quais carros estão a venda;

CREATE OR REPLACE VIEW vw_VeiculoAVenda
AS SELECT * from Veiculo where idVeiculo not in (SELECT idVeiculo from Venda) order by Marca asc, Modelo asc;

-- Procedure para atualizar o Valor de uma compra de pessoa Jurídica

DELIMITER //
CREATE PROCEDURE Atualiza_Valor (IN Valor_Veiculo DECIMAL(7,2), IN Referencia INT)
BEGIN 
	UPDATE Compra_PJ SET Valor = Valor + Valor_Veiculo WHERE Compra_PJ.idCompra_PJ = Referencia;
END;
// 
DELIMITER ;

-- Procedure para atualizar data e hora do pagamento na tabela Venda

DELIMITER //
CREATE PROCEDURE Prc_Set_Time_Venda (IN tempo DATETIME, IN Ref_Vei INT, IN Ref_Cli INT)
BEGIN 
	UPDATE Venda SET Venda.`Dat_Hor_Pag` = tempo WHERE idVeiculo = Ref_Vei and idCliente = Ref_Cli;
END
// 
DELIMITER ;

-- Trigger para atualizar o Valor de uma compra de pessoa Jurídica

DELIMITER //
CREATE TRIGGER Trg_AtualizarValor AFTER INSERT
ON ItemCompra
FOR EACH ROW
BEGIN
	CALL Atualiza_Valor(NEW.Valor, NEW.idCompra_PJ);
END;
 //
DELIMITER ;



-- >>>>>>>>>>>>>>>>>>>>>>>>>>>> INSERÇÃO DE DADOS <<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<
-- -----------------------------------------------------
-- INSERINDO NA TABELA 'bd_svcv.endereco'
-- -----------------------------------------------------
-- SELECT * FROM bd_svcv.Endereco;

INSERT INTO bd_svcv.Endereco (CEP, Rua, Numero, Bairro, Cidade, Estado) 
values ('64255000', 'Padre Aureo', 145, 'Vila Kolping', 'Pedro II', 'PI'),
('64255000', 'Boa Esperança', 86, 'Santa Fé', 'Pedro II', 'PI'), 
('64049548', 'Av. Raul Lopes', 2021, 'Fátima', 'Teresina', 'PI'), 
('64049010', 'Av Joao XXIII', 3565, 'Centro', 'Teresina', 'PI'),
('64255000', 'Av. Coronel Cordeiro', 145, 'Vila Operaria', 'Pedro II', 'PI');

-- -----------------------------------------------------
-- INSERINDO NA TABELA 'bd_svcv.cliente'
-- -----------------------------------------------------
-- SELECT * FROM bd_svcv.Cliente;

INSERT INTO bd_svcv.Cliente (CPF, Nome, Data_Nascimento, Telefone, `E-mail`, idEndereco)
values ('16285767157','Alexandre Vinicius Nascimento','1997-12-04', '81984220981','alexandre.marcos@gmail.com',1),
('79541929389','Noah Raul Silva','1984-02-14', '86997887389','raimundogiovannicarvalho@gmail.com',3),
('16485767157','Odimar Souza Falcao Filho','1996-02-04', '81984247981','odimarfalcao@gmail.com',5),
('61046998394','Jose Medeiros Uchoa','1986-06-14', '81934653276','odimarfalcao@gmail.com',5);

-- -----------------------------------------------------
-- INSERINDO NA TABELA 'bd_svcv.veiculo'
-- -----------------------------------------------------
-- SELECT * FROM bd_svcv.Veiculo;

INSERT INTO bd_svcv.Veiculo (Modelo, Chassi, Marca, Portas, Cor, `Câmbio`, Preco_min, Preco_ven, Ano, Quilometragem)
values ('F-250 Tropicampo CD 3.9 TB Diesel', '9BD178456W1234789', 'Ford', 4, 'Vermelho', 'Automático', 68000, 72589, 2007, 172000),
('Fiat Argo 1.0 Firefly', '9BD178226W1234567', 'Fiat', 4, 'Vermelho', 'Manual', 43000, 45009, 2018, 0),
('Fiat Argo 1.0 Firefly', '9BD178226W6544867', 'Fiat', 4, 'Branco', 'Manual', 43000, 45009, 2018, 0),
('Toyota Corolla Sedan 1.8', '8BD177856X4564567', 'Toyota', 5, 'Amarelo', 'Automático', 49000, 55009, 2015, 55000),
('Toyota Corolla Sedan 1.8', '8BD177345X4486432', 'Toyota', 5, 'Vermelho', 'Automático', 49000, 56009, 2015, 55000),
('Toyota Corolla Sedan 1.8', '8BD177895X5864767', 'Toyota', 5, 'Branco', 'Automático', 49000, 55009, 2015, 55000),
('Toyota Hilux 2.7 SRV 4X4 CD', '8BD177895X5867898', 'Toyota', 4, 'Branco', 'Automático', 89000, 95009, 2015, 60000),
('Toyota Hilux 2.7 SRV 4X4 CD', '8BD177895X5867778', 'Toyota', 4, 'Cinza', 'Automático', 90000, 110009, 2015, 25000),
('Fiat Uno Attractive 1.0 Firefly', '9BD154546W6544867', 'Fiat', 4, 'Cinza', 'Manual', 29000, 37009, 2017, 45000),
('Fiat Uno Attractive 1.0 Firefly', '9BD154546W6567667', 'Fiat', 4, 'Cinza', 'Manual', 32000, 37009, 2017, 34000)
;

-- -----------------------------------------------------
-- INSERINDO NA TABELA 'bd_svcv.fornecedor'
-- -----------------------------------------------------
-- SELECT * FROM bd_svcv.Fornecedor;

INSERT INTO bd_svcv.Fornecedor (Razao_Social, Nome_Fantasia, CNPJ, idEndereco, Telefone)
values ('Newland Veiculos Ltda', 'Newland Toyota', '41597303000544', 3, '8621031300'),
('Jelta Veiculos E Maquinas Ltda', 'Jelta Veiculos', '05385026000380', 4, '8621031470');

-- -----------------------------------------------------
-- INSERINDO NA TABELA 'bd_svcv.funcionario'
-- -----------------------------------------------------
-- SELECT * FROM bd_svcv.Funcionario;

INSERT INTO bd_svcv.Funcionario (CPF, Nome, Usuario, Senha, Data_Nascimento, `E-mail`,Telefone)
values ('1628574567', 'Moises Juliano Santos', 'moises16', '1234', '1995-01-15','moisesp2@gmail.com','86981374534'),
('2357568967', 'Carlos Henrique Gomes', 'carlos23', '1234', '1976-04-23','carlosp2@gmail.com','86995678900');

-- -----------------------------------------------------
-- INSERINDO NA TABELA 'bd_svcv.venda'
-- -----------------------------------------------------
-- select * from venda;
-- truncate table venda;
INSERT INTO bd_svcv.Venda (idCliente, idVeiculo, idFuncionario,Dat_Hor_Venda, Valor)
values (1, 4, 1, '2019-01-18 14:59:00', 58000), (2, 1, 1, '2019-01-19 09:09:00',68000),
(1, 5, 1, '2019-01-20 14:59:00',58000),(4, 6, 1, '2018-12-24 14:59:00',54000);

CALL Prc_Set_Time_Venda ('2019-01-18 14:59:00',4,1); -- Testando Procedure;

-- -----------------------------------------------------
-- INSERINDO NA TABELA 'bd_svcv.compra_pf'
-- -----------------------------------------------------
-- SELECT * FROM bd_svcv.Compra_PF;

INSERT INTO bd_svcv.Compra_PF (idCliente, idVeiculo, idFuncionario, Dat_Hor_Compra)
values (1, 1, 2, '2019-01-18 14:59:00');

-- -----------------------------------------------------
-- INSERINDO NA TABELA 'bd_svcv.compra_pj'
-- -----------------------------------------------------
-- SELECT * FROM bd_svcv.Compra_PJ;

INSERT INTO bd_svcv.Compra_PJ (idFornecedor, Dat_Hor_Compra)
values (1, '2019-01-14 14:59:00');

-- -----------------------------------------------------
-- INSERINDO NA TABELA 'bd_svcv.IemCompra'
-- -----------------------------------------------------
-- SELECT * FROM bd_svcv.ItemCompra;

INSERT INTO bd_svcv.ItemCompra (idCompra_PJ, idVeiculo, Valor)
values (1, 4, 48000), (1, 5, 48000), (1, 6, 48000), (1, 7, 88000),
(1, 8, 89500);  

